### ISSUE TITLE
Integration of LGSVL with Scenario_simulator_v2

### ISSUE THREAD

**Issue by mitsudome-r** [autowarefoundation/autoware-projects#10]
## Description
(copied issue from https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/issues/1444)
Integration of LGSVL with currently used scenario runner (Scenario_simulator_v2 by TierIV)

### Purpose
It's required to run regression tests in LGSVL based on scenarios controlled by scenario_simulator_v2

### Desired Behavior
Working integration, LGSVL controled by scenario_simulator_v2

### Definition of Done  

- [x] LGSVL integrated with scenario_simulator_v2
- [x] Shared code
- [x] Documentation / instruction how to use
- [ ] Test of local execution of SVL + scenario_simulator_v2 based on instruction

**Comment by BonoloAWF** [comment]
No longer valid since the simulator is being replaced.
