### ISSUE TITLE
Assess ITRI's hardware spec for Open AD Kit suitability

### ISSUE THREAD

**Issue by LalithVipulananthan** [autowarefoundation/autoware-projects#12]
As discussed in the Open AD Kit meeting on 2022/03/10, a review was requested of [ITRI's hardware](https://github.com/autowarefoundation/autoware/files/8210975/ITRI.Autonomous.Bus.Pilot.Run.in.Hsinchu.Update_20220308.pdf) to confirm if it would be suitable to run the Open AD Kit. Initial review is expected by March 18th.

**Comment by kasperornmeck** [comment]
@LalithVipulananthan 

The review has been completed and the conclusion is the following:
- the hardware suggested on page 12 from ITRI's hardware PDF is OK to use for Open AD Kit
- the software developed for the Bus ODD needs to build/pass tests/etc successfully in the CI/CD on Arm

Let me know if you have any further questions or comments. Thanks!
